version: "3"
services:
  db:
    container_name: go-mongo-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./database/mongo/mongo-data:/data/db
    networks:
      - go-mongo
    restart: always
  adapter:
    container_name: go-adapter
    image: arvians/go-mongo/adapter
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - go-mongo
    restart: always
  user:
    container_name: go-user-service
    image: arvians/go-mongo/user
    ports:
      - "50001:50001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - go-mongo
    restart: always
  post:
    container_name: go-post-service
    image: arvians/go-mongo/post
    ports:
      - "50002:50002"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - go-mongo
    restart: always

networks:
  go-mongo:
    driver: bridge