// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/arvians-id/go-mongo/user/cmd/config"
	"github.com/arvians-id/go-mongo/user/internal/repository"
	"github.com/arvians-id/go-mongo/user/internal/service"
	"github.com/arvians-id/go-mongo/user/pb"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitServerAPI(configuration config.Config) (pb.UserServiceServer, error) {
	database, err := config.NewInitializedDatabase(configuration)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(database)
	userServiceServer := service.NewUserService(userRepository)
	return userServiceServer, nil
}

// wire.go:

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService)
